management:
  health:
    mail:
      enabled: false
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
server:
  port: 8888
  servlet:
    context-path: /xxl-job-admin
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
    type: com.zaxxer.hikari.HikariDataSource
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  profiles:
    active: dev

jasypt:
  encryptor:
    password: ahfga

sms:
  username: prodAdmin
  password: tes!csget35#d
  baseUrl: https://xm7.cn

#logging:
#  level:
#    com.xxl.job.admin.dao: debug

omg:
  api-secret: 0xqyvkOtUyJAYrA5
  base-url: https://omg.sumwhy.com/manager/openApi/